# Generated by Django 4.0.3 on 2022-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_author_message_created_at_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=6, unique=True),
        ),
    ]
